import {beforeEach,afterEach,expect,it,vi} from 'vitest'
let send: ReturnType<typeof vi.fn>
beforeEach(()=>{vi.resetModules();vi.stubGlobal('__APP_VERSION__','1.23.1');vi.stubEnv('VITE_PALCO_API_URL','https://api-stg.louvorja.com.br');vi.stubEnv('VITE_URL_DATABASE','');vi.stubEnv('VITE_API_FALLBACK_URLS','');vi.stubEnv('VITE_APP_VERSION','');send=vi.fn().mockResolvedValue(new Response());vi.stubGlobal('fetch',send)})
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs()})
async function install(){const {installClientPlatformHeader}=await import('../client-platform');installClientPlatformHeader();return installClientPlatformHeader}
it('identifica API relativa e API configurada, preservando opções e headers',async()=>{await install();await fetch('/v1/custom',{method:'POST',body:'dados',headers:{Authorization:'Bearer token'}});const [url,init]=send.mock.calls[0];expect(url).toBe('/v1/custom');expect(init.method).toBe('POST');expect(init.body).toBe('dados');expect(init.headers.get('Authorization')).toBe('Bearer token');expect(init.headers.get('X-Client-Platform')).toBe('web');expect(init.headers.get('X-Client-Version')).toBe('1.23.1');await fetch(new URL('https://api-stg.louvorja.com.br/v1'));expect(send.mock.calls[1][1].headers.get('X-Client-Platform')).toBe('web')})
it('não marca terceiros, origens parecidas, blob, data ou no-cors',async()=>{await install();for(const url of ['https://example.com/x','https://api.louvorja.com.br.example.com/x','blob:https://example.com/a','data:text/plain,x']){await fetch(url);expect(send.mock.lastCall?.[1]).toBeUndefined()}const init={mode:'no-cors' as const};await fetch('/v1',init);expect(send.mock.lastCall?.[1]).toBe(init)})
it('preserva Request e identidade explícita; instala uma vez',async()=>{const installAgain=await install();const wrapper=fetch;installAgain();expect(fetch).toBe(wrapper);const request=new Request('https://api.louvorja.com.br/v1',{method:'POST',body:'abc',headers:{'X-Client-Platform':'palco'}});await fetch(request);expect(send.mock.lastCall?.[0]).toBe(request);expect(send.mock.lastCall?.[1].headers.get('X-Client-Platform')).toBe('palco');expect(await request.text()).toBe('abc')})
it('não repete chamada quando fetch original lança erro',async()=>{send.mockImplementation(()=>{throw new Error('falha')});await install();expect(()=>fetch('/v1')).toThrow('falha');expect(send).toHaveBeenCalledTimes(1)})
