name: CI review comment

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  checks: read
  contents: read
  issues: write

jobs:
  ci-review:
    uses: Piano-Louvor-JA/.github/workflows-reusable/ci-review-comment.yml@c807392195590da870cadd3fde7f369e73d440db
