name: CI review comment

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  checks: read
  contents: read
  issues: write

jobs:
  ci-review:
    uses: Piano-Louvor-JA/.github/.github/workflows/ci-review-comment.yml@ec22c623e1b8547eef7cc4138904cc4453c6c9a0
